### ISSUE TITLE
progress bar not displaying correctly

### ISSUE THREAD

**Issue by lobachevzky** [erikrose/nose-progressive#87]
Hi,
The issues that I am seeing with the progress bar are as follows:
1. It doesn't show up for the first 30 seconds or so.
2. There is a big empty space between the `nosetests` command and the progressbar.
3. The bar is far to the right side and possible cut-off.
4. From the pictures, it looks like there should be a lightly shaded region that indicates the negative space in the bar. That does not display for my bar.

Here is a picture:
<img width="1415" alt="screen shot 2018-03-07 at 12 50 58 pm" src="https://user-images.githubusercontent.com/10344742/37109034-dce0a49a-2206-11e8-8904-4621cdd6894d.png">

I imagine this has something to do with my terminal settings, although I reproduced the problem in iTerm and Mac Terminal.

I'm not sure what information about my system would be helpful, but I am using `nose-progressive==1.5.1` downloaded from pip and OS X High Sierra 10.13.3.

**Comment by erikrose** [comment]
2 and 3 are supposed to happen. Putting the bar at the bottom is the only way to preserve the scrolled-offscreen text while also showing a progress bar; I had to do some fancy tricks to get that to work. The bar is purposely small to leave room for full test pathnames to its left, which got quite long in the Django app I was developing when I built this.

For 1, do you mean the tests are obviously running but the bar doesn't appear?

For 4, try a light background color. I always use white, so the defaults might not suit you (though they are settable via env vars among other ways).

**Comment by lobachevzky** [comment]
Ok, with a different background I was able to see the bar. The fact that the bar doesn't appear for the first few seconds is a little surprising. I've double checked and without `--with-progressive` the `.` characters from normal `nose` tests appear immediately.

**Comment by erikrose** [comment]
What you're seeing is probably the result of collecting the tests twice: once to get a count for the progress bar and again to actually run them. Nose test suites are lazy and so are destroyed by iterating over them. It may be possible to trade some RAM for some speed if you wanted to try a patch. See `prepareTestLoader()` if you're curious.

**Comment by erikrose** [comment]
Is your test suite humongous? That's the only way it should take 30 seconds. I've never seen that kind of delay on my 1000-test suites (or I would have sought an optimization).
