### ISSUE TITLE
'dict' object has no attribute 'SubjectID'

### ISSUE THREAD

**Issue by pawaskumarsingh** [erikrose/nose-progressive#88]
sub = MaanyaIT_EXAM48_ManageSubject.objects.all()
    for pl in sub:
        sbj = {}
        sbj['SubjectID']= pl.SubjectID
        subname = TempTableForExamQuestions.objects.filter(SubjectID=int(pl.SubjectID)).values('SubjectID').distinct()
        sb = []
        for sname in subname:
            sbn = {}
            sbn['SubjectName'] = str(sname.SubjectID)
            ques = TempTableForExamQuestions.objects.filter(SubjectID=int(pl.SubjectID)).count()
            sbn['count']=ques
            sb.append(sbn)
        sbj['quest'] = sb
        results.append(sbj)
        
    context={
        'results':results,
        }
    return render(request,'exam48app/TableForExamQuestions.html', context)

when i use distinct then i will get this error:''dict' object has no attribute 'SubjectID''.

**Comment by erikrose** [comment]
I don't think this has anything to do with nose-progressive.
